# Generated by Django 5.2.14 on 2026-05-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Medicamento')),
                ('dosagem', models.CharField(max_length=50, verbose_name='Dosagem')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_critico', models.IntegerField(default=10, verbose_name='Nível de Alerta')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='CPF ou Prontuário')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
