# Generated by Django 5.2.14 on 2026-05-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída (Baixa)')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('crm', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM do Médico')),
                ('nome_medico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Médico')),
                ('endereco_saida', models.TextField(blank=True, null=True, verbose_name='Endereço (na Baixa)')),
                ('telefone_saida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (na Baixa)')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='website.medicamento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='website.paciente')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
